modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="bubble_gum_simulator"
version="1.0.0"
displayName="Bubble Gum Simulator"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Shane, MCreator"

[[dependencies.bubble_gum_simulator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




